In [2]:
import numpy as np
import pandas as pd
import os
import seaborn as sbn
import gc
#gc.collect()
#建模需要导入的库
from sklearn.linear_model import LogisticRegression as LR

In [3]:
#输入文件
DATA_PATH = os.path.join(os.getcwd(),'data','simply_id','input')
NEW_TRAIN  =  os.path.join(DATA_PATH,'new_train.csv')
NEW_TEST = os.path.join(DATA_PATH,'new_test.csv')

In [4]:
train = pd.read_csv(NEW_TRAIN)
test = pd.read_csv(NEW_TEST)

In [5]:
train = train[['target','song_id_re_rate', 'song_length_re_rate', 'song_year_re_rate',
       'first_genre_id_re_rate', 'artist_name_id_re_rate',
       'lyricist_id_re_rate', 'language_id_re_rate','msno_re_rate','city_re_rate', 'registered_via_re_rate',
          'registration_init_time_re_rate','op_type_re_rate' ]]
test = test[['target','song_id_re_rate', 'song_length_re_rate', 'song_year_re_rate',
       'first_genre_id_re_rate', 'artist_name_id_re_rate',
       'lyricist_id_re_rate', 'language_id_re_rate','msno_re_rate','city_re_rate', 'registered_via_re_rate',
          'registration_init_time_re_rate','op_type_re_rate' ]]
train = train.fillna(train.mean())
test = test.fillna(test.mean())

In [6]:
X_train = train.drop(['target'], axis=1).values
y_train = train['target'].values
X_test = test.drop(['target'], axis=1).values
y_test = test['target'].values

In [7]:
lr = LR()   #建立逻辑回归模型
%time lr.fit(X_train,y_train)  #用筛选后的特征数据来训练模型

Wall time: 34.3 s


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
lr.score(X_test,y_test)   #给出模型的平均正确率

0.67681679722390897

In [9]:
from sklearn import metrics
from scipy import interp 
cm_train = metrics.confusion_matrix(y_train,lr.predict(X_train))  #训练样本的混淆矩阵
print(cm_train)
cm_test = metrics.confusion_matrix(y_test,lr.predict(X_test))  #训练样本的混淆矩阵
print(cm_test)

[[1432368  840961]
 [ 698144 1896378]]
[[353976 214034]
 [179268 469685]]


In [10]:
train_rate = metrics.roc_auc_score(y_train,lr.predict(X_train))
test_rate = metrics.roc_auc_score(y_train,lr.predict(X_train)

SyntaxError: unexpected EOF while parsing (<ipython-input-10-0fc2f4c5e94f>, line 2)

In [8]:
#模型评价
from sklearn import metrics
from scipy import interp 
cm_train = metrics.confusion_matrix(y_train,lr.predict(X_train).round())  #训练样本的混淆矩阵
print(cm_train)
cm_test = metrics.confusion_matrix(y_test,lr.predict(X_test).round())  #训练样本的混淆矩阵
print(cm_test)

[[1432368  840961]
 [ 698144 1896378]]
[[353976 214034]
 [179268 469685]]
